### ISSUE TITLE
pattern can take a regexp?

### ISSUE THREAD

**Issue by matthewmueller** [standardschema/javascript#29]
Trying out this library :-) It's a bit weird that pattern needs to be a string since it forces you to escape your regexp. Example:

``` js
const validate = compile(new Types.Object({
  properties: {
    job: new Types.String({ pattern: '^[\\w:]+$' }),
    time: new Types.String({ pattern: '^\\d{1,2}:\\d{1,2}$' }),
    timezone: new Types.String()
  }
}))
```

Might be nice to make it support regexp too

**Comment by blakeembrey** [comment]
I think this will be a good change. I'll try to accept more JavaScript types and just have that serialise down into a different representation in the future - makes more sense, thanks! 😄
