### ISSUE TITLE
Investigate a validation system using composition only

### ISSUE THREAD

**Issue by blakeembrey** [standardschema/javascript#6]
For example:

``` ts
const createdSchema = compose([
  new Types.Properties({
    dateCreated: compose([new Types.Date()])
  })
])

const userSchema = compose([
  new Types.Properties({
    username: compose([new Types.String(), new Types.Pattern('^[a-zA-Z0-9_-]+$')]),
    password: compose([new Types.String(), new Types.MinLength(5), new Types.MaxLength(100)])
  }),
  createdSchema
])
```
- How do this interact with serialising and deserialising? E.g. when does one serialise/deserialise a type in the chain above?
- This _feels_ more powerful, but the serialised representation is terrible (hard to read)
- Rules become dependent on order, may be confusing? E.g. when does one serialise the type in the chain, especially recursively? Imagine Falcor paths that needs to ignore object outputs.

**Comment by matthewmueller** [comment]
Looks good :-)

This may be too opaque, but I may bundle the `compose` function as what `Types(...)` does.

You may also try:

```js
new Types.Properties({
    username: Types.String().Pattern('^[a-zA-Z0-9_-]+$')])
})
```

One example I found was good to test your validator against a confirm password form, where there's a relationship between the two fields and they have their own constraints (like minLength)

**Comment by blakeembrey** [comment]
Makes sense, I definitely want to make references first-class soon too. I'll log a new issue with thoughts around that, but I think it'll be a new native type that everything in the system can resolve at runtime. Something like (using the current implementation):

```ts
new Types.Object({
  password: new Types.String({ minLength: 5, maxLength: 100 })
  confirmPassword: new Types.String({ 
    uses: [
      new Types.EqualTo({ value: new Types.Ref({ path: 'password' }) })
    ] 
  })
})
```

I implemented the `uses` feature as a bit of a workaround for some out-of-band validation I needed last week - but it's beginning to look for like the correct way. The composed method above, although amazingly powerful and simple, seems to have a lot of theoretical limitations outside of validation which I can't work without (the biggest being serialisation to another type structure). 

Also, the above system is incredibly verbose - I'd love to bring it back to simplicity later. By making every piece a type/rule it's a very simple system that's nice and re-usable. For instance:

```ts
new Types.Object({
  properties: {
    range: new Types.Tuple({
      tuple: [
        new Types.Number({ min: 0, max: new Types.Ref({ path: '1' }) }),
        new Types.Number({ min: new Types.Ref({ path: '0' }) })
      ]
    })
  }
})
```

Eventually, perhaps, `Types.Ref` could even include some valuation rules to get properties from the values too and you could dictate that the max can't be larger than the string value on the same object.

**Comment by blakeembrey** [comment]
@matthewmueller Took a stab at reference types - pretty simple and nice to use. Will be way more powerful once I add some more logic/flow rules. See https://github.com/blakeembrey/jaywalk/blob/master/src/test/number.spec.ts#L28-L37. 

As for composing, I've enabled `uses: Rule[]` in recent code and this feels like it's powerful enough. I have also implement synchronous structural type checking which helps when picking a branch during serialisation. If I could solve serialisation and clearer errors, I'd love to go all in with the composition pattern.
